'use strict';
const skills=[
['Bi','Power BI','analytics','Interactive dashboards, enterprise reporting, and semantic models that make complex business questions easier to answer.'],
['Fa','Microsoft Fabric','platforms','Lakehouse, Warehouse, Dataflow Gen2, and Data Pipelines for end-to-end enterprise analytics.'],
['Sq','SQL','development','Data extraction, transformation, and query optimization using T-SQL and relational databases.'],
['Dx','DAX','analytics','Advanced measures, time intelligence, and business logic for performant Power BI semantic models.'],
['Pq','Power Query','analytics','Connect, clean, and transform data from multiple sources into reliable reporting foundations.'],
['Sn','Snowflake','platforms','Cloud data integration and analytics, with pipelines connecting Snowflake to enterprise reporting.'],
['Pa','Power Apps','automation','Canvas and model-driven applications that connect operational workflows with business data.'],
['Au','Power Automate','automation','Automated approvals, custom connectors, and workflows that reduce repetitive manual steps.'],
['Dv','Dataverse','platforms','Connected business data for Power Platform applications and enterprise process automation.'],
['Py','Python','development','Data analysis and automation to support analytics development and repeatable workflows.'],
['Az','Azure','platforms','Azure Data Factory, Azure Functions, and identity services supporting enterprise data solutions.'],
['Dl','Direct Lake','analytics','Fabric semantic models connecting lakehouse data with responsive Power BI reporting.'],
['Gi','Git','development','Version control and CI/CD practices for reliable, maintainable BI delivery.'],
['Ai','Copilot Studio','automation','Data-driven agents and intelligent workflows that help business users access insights.'],
['Rs','Row-Level Security','analytics','Role-based access and secure reporting so users see the data appropriate to their responsibilities.']
];
const grid=document.getElementById('skills-grid');
function selectSkill(index){const s=skills[index];document.getElementById('skill-symbol').textContent=s[0];document.getElementById('skill-name').textContent=s[1];document.getElementById('skill-category').textContent=s[2]==='platforms'?'DATA PLATFORMS':s[2].toUpperCase();document.getElementById('skill-description').textContent=s[3];grid.querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('selected',i===index);b.setAttribute('aria-pressed',String(i===index))})}
skills.forEach((s,i)=>{const b=document.createElement('button');b.className='skill'+(i===0?' selected':'');b.dataset.category=s[2];b.setAttribute('aria-label','Explore '+s[1]);b.setAttribute('aria-pressed',String(i===0));b.innerHTML=`<span class="skill-number">${String(i+1).padStart(2,'0')}</span><span class="skill-symbol">${s[0]}</span><span class="skill-name">${s[1]}</span>`;b.addEventListener('click',()=>selectSkill(i));grid.appendChild(b)});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const f=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});grid.querySelectorAll('button').forEach(b=>b.classList.toggle('filtered',f!=='all'&&b.dataset.category!==f));const first=skills.findIndex(s=>f==='all'||s[2]===f);selectSkill(first)}));
const cases={driver:{label:'WM / ENTERPRISE OPERATIONS',title:'Driver performance, clearly connected.',problem:'Operational teams need a consistent view of driver and route performance across business units, with reporting that supports daily decisions and executive oversight.',solution:'Delivered enterprise Power BI dashboards, advanced DAX measures, KPIs, and semantic models for driver performance across 7+ business units. Built operational and executive reporting for route managers.',result:'30% workflow efficiency improvement',detail:'Reported for the driver performance dashboard initiative in my résumé.',stack:'Power BI · DAX · Semantic modeling · Row-Level Security'},fabric:{label:'WM / MICROSOFT FABRIC',title:'A foundation for faster insights.',problem:'Enterprise analytics relies on data from multiple systems. Reporting needs a connected foundation that can handle scale and support responsive insights.',solution:'Implemented Microsoft Fabric Lakehouse, Data Pipelines, and Direct Lake models. Engineered pipelines integrating Snowflake, SQL Server, SharePoint, APIs, and Fabric, handling 5M+ records.',result:'65% report performance improvement',detail:'Reported for the end-to-end Fabric initiative in my résumé.',stack:'Microsoft Fabric · Lakehouse · Data Pipelines · Direct Lake · Snowflake'},automation:{label:'WM / POWER PLATFORM',title:'From manual steps to smarter workflows.',problem:'Repeated manual tasks and exception handling slow down operational processes and make routine work harder to coordinate.',solution:'Built Power Apps and automated Power Automate workflows for 10+ business processes, including UKG/Kronos timecard exception management. Re-architected an existing Power Apps application for improved performance.',result:'10+ business processes supported',detail:'Application and workflow scope documented in my résumé.',stack:'Power Apps · Power Automate · Dataverse · Business process automation'}};
const dialog=document.getElementById('case-dialog');let opener;
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{const c=cases[b.dataset.project];opener=b;document.getElementById('case-label').textContent=c.label;document.getElementById('case-title').textContent=c.title;document.getElementById('case-content').innerHTML=`<h3>The business need</h3><p>${c.problem}</p><h3>What I built</h3><p>${c.solution}</p><div class="result"><strong>${c.result}</strong><p>${c.detail}</p></div><h3>Technology</h3><p>${c.stack}</p><p class="case-note">Project descriptions and outcomes are drawn from my résumé. Visual previews are illustrative, not screenshots of employer systems.</p>`;dialog.showModal();document.body.style.overflow='hidden'}));
function closeCase(){dialog.close()}
dialog.querySelector('.dialog-close').addEventListener('click',closeCase);dialog.querySelector('.dialog-done').addEventListener('click',closeCase);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeCase()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';opener?.focus()});
const navLinks=[...document.querySelectorAll('nav a')];const sectionObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){navLinks.forEach(a=>{const active=a.hash==='#'+e.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('main>section').forEach(s=>sectionObserver.observe(s));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');e.target.classList.remove('ready');revealObserver.unobserve(e.target)}}),{threshold:.05});document.querySelectorAll('.about-grid,.proof-strip,.stack-layout,.project,.journey,.contact h2').forEach(el=>{el.classList.add('reveal','ready');revealObserver.observe(el)})}
document.getElementById('year').textContent=new Date().getFullYear();
